#pragma once
#include "../grx/GcConstrainedGeometry.h"
#include "acad2grx.h"

#define AcConstrainedConstructionLine	GcConstrainedConstructionLine
#define AcConstrained2PointsConstructionLine	GcConstrained2PointsConstructionLine
#define AcConstrainedDatumLine	GcConstrainedDatumLine
#define AcConstrainedArc	GcConstrainedArc
#define AcConstrainedBoundedEllipse	GcConstrainedBoundedEllipse
#define AcConstrainedBoundedLine	GcConstrainedBoundedLine
#define AcDbAssocTransInfo GcDbAssocTransInfo
#define AcConstrainedGeometryDraggingInfo GcConstrainedGeometryDraggingInfo