#pragma once
#include "../grx/GcFdUiFormatDialog.h"
#include "acad2grx.h"
#include "AcFdUiFormatList.h"

#define ACFDUI_UM_FORMAT_CHANGED        GCFDUI_UM_FORMAT_CHANGED
#define ACFDUI_UM_BEGIN_FORMATEX_DIALOG GCFDUI_UM_BEGIN_FORMATEX_DIALOG
#define ACFDUI_UM_END_FORMATEX_DIALOG   GCFDUI_UM_END_FORMATEX_DIALOG

#define ACFDUI_FDSTYLE_SIMPLE       GCFDUI_FDSTYLE_SIMPLE
#define ACFDUI_FDSTYLE_FILENAME     GCFDUI_FDSTYLE_FILENAME
#define ACFDUI_FDSTYLE_DOUBLE       GCFDUI_FDSTYLE_DOUBLE
#define ACFDUI_FDSTYLE_DOUBLE_POINT GCFDUI_FDSTYLE_DOUBLE_POINT
#define ACFDUI_FDSTYLE_ALL          GCFDUI_FDSTYLE_ALL

#define CAcFdUiFormatDialog   CGcFdUiFormatDialog
