#pragma once
#include "../grx/GcPointCloud.h"
#include "acad2grx.h"

#define AcViewFrustum GcViewFrustum
#define AcPcPointFloat GcPcPointFloat
#define AcPcPointDouble GcPcPointDouble
#define AcPcPointAttributes GcPcPointAttributes
#define IAcPcDataBuffer IGcPcDataBuffer
#define IAcPcPointFilter IGcPcPointFilter
#define IAcPcPointFilter IGcPcPointFilter
#define IAcPcPointProcessor IGcPcPointProcessor
#define AcPointCloudViewFrustum GcPointCloudViewFrustum


#define acdbCreatePointCloudEntity gcdbCreatePointCloudEntity
#define acdbAttachPointCloudExEntity gcdbAttachPointCloudExEntity
#define acdbAttachPointCloudEntity gcdbAttachPointCloudEntity
#define acdbModifyPointCloudDataView gcdbModifyPointCloudDataView
#define acdbResetPointCloudDataView gcdbResetPointCloudDataView
#define acdbSetPointCloudFilter gcdbSetPointCloudFilter
#define acdbProcessPointCloudData gcdbProcessPointCloudData

