#pragma once
#include "../grx/Gsoft.h"
#include "acad2grx.h"


#define Adesk_Boolean_is_bool Gsoft_Boolean_is_bool
#define Adesk_Int32_is_int Gsoft_Int32_is_int
#define _ADESK_CROSS_PLATFORM_ _GSOFT_CROSS_PLATFORM_
#define ADESK_DEPRECATED GSOFT_DEPRECATED
#define ADESK_DEPRECATED_MSG GSOFT_DEPRECATED_MSG
#define ADESK_DATA_IMPORT GSOFT_DATA_IMPORT
#define ADESK_PACK_BEGIN GSOFT_PACK_BEGIN
#define ADESK_PACK_END GSOFT_PACK_END
#define ADESK_OVERRIDE GSOFT_OVERRIDE
#define ADESK_SEALED GSOFT_SEALED
#define ADESK_SEALED_VIRTUAL GSOFT_SEALED_VIRTUAL
#define ADESK_FORCE_INLINE GSOFT_FORCE_INLINE
#define _ADESK_WINDOWS_ _GCAD_WINDOWS_
#define ADESK_UNREFED_PARAM GSOFT_UNREFED_PARAM
#define ADESK_UNREACHABLE GSOFT_UNREACHABLE
#define _AC64 _GC64