#pragma once
#include "../grx/gxdispids.h"
#include "acad2grx.h"

#define DISPID_ACADCOLOR         DISPID_GCADCOLOR
#define DISPID_ACADLAYER         DISPID_GCADLAYER
#define DISPID_ACADLINETYPE      DISPID_GCADLINETYPE
#define DISPID_ACADLINETYPESCALE DISPID_GCADLINETYPESCALE
#define DISPID_ACADPLOTSTYLENAME DISPID_GCADPLOTSTYLENAME
#define DISPID_ACADLINEWEIGHT    DISPID_GCADLINEWEIGHT
#define DISPID_ACADHYPERLINKS    DISPID_GCADHYPERLINKS
#define DISPID_ACADMATERIAL      DISPID_GCADMATERIAL
#define DISPID_ACADVISUALSTYLE   DISPID_GCADVISUALSTYLE
