#pragma once
#include "../grx/dbacis.h"
#include "acad2grx.h"
#include "acdbport.h"

#define acdbGetModelerDwgVer gcdbGetModelerDwgVer
#define acdbModelerSaveEntityToDwgFiler gcdbModelerSaveEntityToDwgFiler
#define acdbModelerSaveEntitiesToDwgFiler gcdbModelerSaveEntitiesToDwgFiler
#define acdbModelerSaveEntityToDxfFiler gcdbModelerSaveEntityToDxfFiler
#define acdbModelerSaveEntitiesToDxfFiler gcdbModelerSaveEntitiesToDxfFiler
#define acdbModelerRestoreEntityFromDwgFiler gcdbModelerRestoreEntityFromDwgFiler
#define acdbModelerRestoreEntitiesFromDwgFiler gcdbModelerRestoreEntitiesFromDwgFiler
#define acdbModelerRestoreEntityFromDxfFiler gcdbModelerRestoreEntityFromDxfFiler
