#pragma once
#include "../grx/dbdimassoc.h"
#include "acad2grx.h"

#define acdbUpdateDimension gcdbUpdateDimension
#define acdbUpdateAllDimensions gcdbUpdateAllDimensions
#define acdbGetDimAssocId gcdbGetDimAssocId
#define acdbGetDimAssocIds gcdbGetDimAssocIds
#define acdbIsTransSpatial gcdbIsTransSpatial
#define acdbGetAssocAnnotationActionBody gcdbGetAssocAnnotationActionBody
#define acdbGetNonAssocAnnotations gcdbGetNonAssocAnnotations
#define acdbIsEntityInBlockOrXref gcdbIsEntityInBlockOrXref
#define acdbIsAnnoMonitorOn gcdbIsAnnoMonitorOn
#define acdbIsAssociativityAlertIconDisabled gcdbIsAssociativityAlertIconDisabled
#define acdbDisableAssociativityAlertIcon gcdbDisableAssociativityAlertIcon
#define acdbIsAssociativeAnnotation gcdbIsAssociativeAnnotation

#define AcDbAnnoAlertDisabler GcDbAnnoAlertDisabler
#define acdbGetAssociativityOverride gcdbGetAssociativityOverride
#define acdbSetAssociativityOverride gcdbSetAssociativityOverride

