#pragma once
#include "../grx/dbsymutl.h"
#include "acad2grx.h"

#define ACDBSYMUTIL_SERVICES_CURRENT_VERSION    GCDBSYMUTIL_SERVICES_CURRENT_VERSION
#define ACDBSYMUTIL_SERVICESNAME_WITH_VERSION_1 GCDBSYMUTIL_SERVICESNAME_WITH_VERSION_1
#define ACDBSYMUTIL_SERVICESNAME_WITH_VERSION   GCDBSYMUTIL_SERVICESNAME_WITH_VERSION
#define ACDBSYMUTIL_SERVICES_NAME               GCDBSYMUTIL_SERVICES_NAME

