#pragma once
#include "../grx/dbtexteditor.h"
#include "acad2grx.h"

#define AcDbTextEditorLocation GcDbTextEditorLocation
#define AcDbTextEditorSelectable GcDbTextEditorSelectable
#define AcDbTextEditorSelectionBase GcDbTextEditorSelectionBase
#define AcDbTextEditorSelection GcDbTextEditorSelection
#define AcDbTextEditorParagraph GcDbTextEditorParagraph
#define AcDbTextEditorStack GcDbTextEditorStack
#define AcDbTextEditorCursor GcDbTextEditorCursor
#define AcDbTextEditorColumn GcDbTextEditorColumn
#define AcDbTextEditorParagraphTab GcDbTextEditorParagraphTab
#define AcDbTextEditorParagraphIterator GcDbTextEditorParagraphIterator
#define AcDbTextEditor GcDbTextEditor
#define AcDbTextEditorColumns GcDbTextEditorColumns
#define AcDbTextEditorWipeout GcDbTextEditorWipeout