#pragma once
#include "../grx/dbxutil.h"
#include "../grx/dbxutilTodo.h"
#include "acad2grx.h"

//dbxutil.h

#define acdbGetMappedFontName gcdbGetMappedFontName

#define acdbQueueAnnotationEntitiesForRegen gcdbQueueAnnotationEntitiesForRegen

#define acdbPSLayoutAnnoAllVisible gcdbPSLayoutAnnoAllVisible

#define acdbCreateViewByViewport gcdbCreateViewByViewport

#define acdbForceTextAdjust gcdbForceTextAdjust


//dbxutilTodo
#define acdbValidateDbConsistency gcdbValidateDbConsistency

#define acdbOleHitTest gcdbOleHitTest

#define acdbOleGetRotationMatrix gcdbOleGetRotationMatrix

#define acdbOleGetOriginalWidthHeight gcdbOleGetOriginalWidthHeight

#define acdbOleSetOriginalWidthHeight gcdbOleSetOriginalWidthHeight

#define acdbOleGetSelectedFontName gcdbOleGetSelectedFontName

#define acdbOleSetSelectedFontName gcdbOleSetSelectedFontName

#define acdbOleGetSelectedFontPointSize gcdbOleGetSelectedFontPointSize

#define acdbOleSetSelectedFontPointSize gcdbOleSetSelectedFontPointSize

#define acdbOleGetSelectedTextSizeInAcadUnits gcdbOleGetSelectedTextSizeInGcadUnits

#define acdbOleSetSelectedTextSizeInAcadUnits gcdbOleSetSelectedTextSizeInGcadUnits

#define acdbOleGetOriginalSelectedFontName gcdbOleGetOriginalSelectedFontName

#define acdbOleSetOriginalSelectedFontName gcdbOleSetOriginalSelectedFontName

#define acdbOleGetOriginalSelectedFontPointSize gcdbOleGetOriginalSelectedFontPointSize

#define acdbOleSetOriginalSelectedFontPointSize gcdbOleSetOriginalSelectedFontPointSize

#define acdbOleGetOriginalSelectedTextSizeInAcadUnits gcdbOleGetOriginalSelectedTextSizeInGcadUnits

#define acdbOleSetOriginalSelectedTextSizeInAcadUnits gcdbOleSetOriginalSelectedTextSizeInGcadUnits

#define acdbGetDimTextBackground gcdbGetDimTextBackground

#define acdbSetDimTextBackground gcdbSetDimTextBackground

#define acdbGetDimExtensionLength gcdbGetDimExtensionLength

#define acdbSetDimExtensionLength gcdbSetDimExtensionLength

#define acdbGetFixedLengthExtLineEnabled gcdbGetFixedLengthExtLineEnabled

#define acdbSetFixedLengthExtLineEnabled gcdbSetFixedLengthExtLineEnabled

#define acdbSetFixedLengthExtLineEnabled gcdbSetFixedLengthExtLineEnabled

#define acdbGetArcLengthSymbolPlacement gcdbGetArcLengthSymbolPlacement

#define acdbSetArcLengthSymbolPlacement gcdbSetArcLengthSymbolPlacement

#define acdbGetDimLineLinetype gcdbGetDimLineLinetype

#define acdbSetDimLineLinetype gcdbSetDimLineLinetype

#define acdbSetDimExt1Linetype gcdbSetDimExt1Linetype

#define acdbGetDimExt1Linetype gcdbGetDimExt1Linetype

#define acdbSetDimExt2Linetype gcdbSetDimExt2Linetype

#define acdbGetDimExt2Linetype gcdbGetDimExt2Linetype

#define acdbGetLargeRadDimJogAngle gcdbGetLargeRadDimJogAngle

#define acdbSetLargeRadDimJogAngle gcdbSetLargeRadDimJogAngle

#define acdbGetDimFlipArrow gcdbGetDimFlipArrow

#define acdbSetDimFlipArrow gcdbSetDimFlipArrow

#define acdbGetDimFlipArrowWhich gcdbGetDimFlipArrowWhich

#define acdbSetDimFlipArrowWhich gcdbSetDimFlipArrowWhich

#define acdbGetExemptCheckFlag gcdbGetExemptCheckFlag

#define acdbSetExemptCheckFlag gcdbSetExemptCheckFlag

#define acdbGetDimJogSymbolSize gcdbGetDimJogSymbolSize

#define acdbSetDimJogSymbolSize gcdbSetDimJogSymbolSize

#define acdbGetDimJogSymbolPosition gcdbGetDimJogSymbolPosition

#define acdbSetDimJogSymbolPosition gcdbSetDimJogSymbolPosition

#define acdbGetRadialExtensionAngles gcdbGetRadialExtensionAngles

#define acdbSetRadialExtensionAngles gcdbSetRadialExtensionAngles

#define acdbGetDimAngExtOn gcdbGetDimAngExtOn

#define acdbSetDimAngExtOn gcdbSetDimAngExtOn

#define acdbGetDimTolAlign gcdbGetDimTolAlign

#define acdbSetDimTolAlign gcdbSetDimTolAlign

#define acdbGetDimBreakSize gcdbGetDimBreakSize

#define acdbSetDimBreakSize gcdbSetDimBreakSize

#define acdbIsInLongTransaction gcdbIsInLongTransaction

#define AcDbDisableAnnoAutoScale GcDbDisableAnnoAutoScale

#define acdbGetVisualStyleIndexById gcdbGetVisualStyleIndexById

#define acdbGetVisualStyleIndexByName gcdbGetVisualStyleIndexByName

#define acdbGetVisualStyleIdByIndex gcdbGetVisualStyleIdByIndex

#define acdbAddConstrainedGeometryDraggingInfo gcdbAddConstrainedGeometryDraggingInfo
