#pragma once
#include "../grx/idver.h"
#include "acad2grx.h"

#define  AC_BLDENV        GC_BLDENV
#define  ACADV_BLDMAJOR   GCADV_BLDMAJOR
#define  ACADV_BLDMINOR   GCADV_BLDMINOR
#define  ACADV_BLDBRANCH  GCADV_BLDBRANCH
#define  ACADV_BLDSTREAM  GCADV_BLDSTREAM

#define  ACADV_RCFILEVER1  GCADV_RCFILEVER1
#define  ACADV_RCFILEVER2  GCADV_RCFILEVER2
#define  ACADV_RCFILEVER3  GCADV_RCFILEVER3
#define  ACADV_RCFILEVER4  GCADV_RCFILEVER4
#define  ACADV_RCFILEVER5  GCADV_RCFILEVER5

#define  ACADV_RELMAJOR    GCADV_RELMAJOR
#define  ACADV_RELMINOR    GCADV_RELMINOR

#define  ACADV_RCFILEVER1_CORRECTION  GCADV_RCFILEVER1_CORRECTION

#define  ACADV_RCFILEVERSTR  GCADV_RCFILEVERSTR
#define  ACADV_PRODVERSION   GCADV_PRODVERSION
#define  ACAD_COPYRIGHT_YEAR GCAD_COPYRIGHT_YEAR

#define  ACADV_VERNUM     GCADV_VERNUM
#define  ACADV_VERNAME    GCADV_VERNAME
#define  ACADV_VERFULL    GCADV_VERFULL
#define  ACADV_BLDVERSTR  GCADV_BLDVERSTR
#define  ACAD_COPYRIGHT   GCAD_COPYRIGHT

#define  ACAD_TLBVERSION_MAJOR  GCAD_TLBVERSION_MAJOR
#define  ACAD_TLBVERSION_MINOR  GCAD_TLBVERSION_MINOR
#define  ACAD_TLBVERSION        GCAD_TLBVERSION
#define  ACAD_TLBVERSIONSTR     GCAD_TLBVERSIONSTR
#define  ACDB_TLBVERSION_MAJOR  GCDB_TLBVERSION_MAJOR
#define  ACDB_TLBVERSION_MINOR  GCDB_TLBVERSION_MINOR
#define  ACDB_TLBVERSIONSTR     GCDB_TLBVERSIONSTR
#define  ACDB_TLBVERSION        GCDB_TLBVERSION