#pragma once
#include "../grx/rxboiler.h"
#include "acad2grx.h"

#define acrxFindAcRxClass  gcrxFindGcRxClass
#define ACRX_DECLARE_MEMBERS_EXPIMP GCRX_DECLARE_MEMBERS_EXPIMP
#define ACRX_DXF_DEFINE_MEMBERS_WITH_PROPERTIES GCRX_DXF_DEFINE_MEMBERS_WITH_PROPERTIES
#define ACRX_NO_CONS_DEFINE_MEMBERS_WITH_PROPERTIES GCRX_NO_CONS_DEFINE_MEMBERS_WITH_PROPERTIES