#pragma once
#include "afxole.h"
#include "../grx/rxmfcapi.h"
#include "acad2grx.h"

#define AcedPreTranslateMsgFn GcedPreTranslateMsgFn
#define acedSuppressFileMRU gcedSuppressFileMRU
#define acedGetApplicationFrame gcedGetApplicationFrame
#define acedGetChildFrameSettings gcedGetChildFrameSettings
#define acedGetAcadBrandingResourceInstance gcedGetGcadBrandingResourceInstance
#define acedRemoveMainFramePreTranslateObserver gcedRemoveMainFramePreTranslateObserver
#define acedRegisterMainFramePreTranslateObserver gcedRegisterMainFramePreTranslateObserver