#pragma once
#include "../grx/rxnames.h"
#include "acad2grx.h"

#define ACRX_CLASS_DICTIONARY          GCRX_CLASS_DICTIONARY
#define ACRX_DYNAMIC_LINKER            GCRX_DYNAMIC_LINKER
#define ACRX_SERVICE_DICTIONARY        GCRX_SERVICE_DICTIONARY
#define ACRX_KERNEL_SERVICES           GCRX_KERNEL_SERVICES
#define ACRX_CLASS_DICTIONARY          GCRX_CLASS_DICTIONARY
#define ACRX_PROTOCOL_REACTOR_MANAGER  GCRX_PROTOCOL_REACTOR_MANAGER