#pragma once
#include "gcadstd.h"
#include <assert.h>
#include "dbmain.h"
#include "dbdict.h"
#include "dbdate.h"
#include "../Ge/GeVector2d.h"
#include "../DbSymUtl.h"

#define GCDBSYMUTIL_SERVICES_CURRENT_VERSION    ODDBSYMUTIL_SERVICES_CURRENT_VERSION
#define GCDBSYMUTIL_SERVICESNAME_WITH_VERSION_1 ODDBSYMUTIL_SERVICESNAME_WITH_VERSION_1
#define GCDBSYMUTIL_SERVICESNAME_WITH_VERSION   ODDBSYMUTIL_SERVICESNAME_WITH_VERSION
#define GCDBSYMUTIL_SERVICES_NAME               ODDBSYMUTIL_SERVICES_NAME

