#ifndef   _ID_H
#define   _ID_H

#define  GCADV_RELMAJOR  ODADV_RELMAJOR
#define  GCADV_RELMINOR  ODADV_RELMINOR

#define ODADV_RELMAJOR  22
#define ODADV_RELMINOR  0

#define ASM_FILE_RELMAJOR  223
#define ASM_FILE_RELMINOR  0
#define ASM_FILE_RELPOINT  1
#define ASM_FILE_RELPATCH  1930
#define ASM_PROD_RELMAJOR  223
#define ASM_PROD_RELMINOR  0
#define ASM_PROD_RELPOINT  1
#define ASM_PROD_RELPATCH  1930
#endif
