#pragma once
#include "../RxBoiler.h"

#define gcrxFindGcRxClass           odrxFindOdRxClass
#define GCRX_DEFINE_GPDESC          ODRX_DEFINE_GPDESC
#define GCRX_DECLARE_GPDESC         ODRX_DECLARE_GPDESC
#define gcrxInstantiateClass        odrxInstantiateClass
#define GCRX_DECLARE_MEMBERS_EXPIMP ODRX_DECLARE_MEMBERS_EXPIMP
#define GCRX_EMPTY                  ODRX_EMPTY
#define GCRX_DECLARE_MEMBERS        ODRX_DECLARE_MEMBERS
#define GCRX_DEFINE_MEMBERS3        ODRX_DEFINE_MEMBERS3
#define gcrx_abort                  odrx_abort
#define GCRX_STATIC_CHECK           ODRX_STATIC_CHECK
#define GCRX_NO_CONS_DEFINE_MEMBERS ODRX_NO_CONS_DEFINE_MEMBERS
#define GCRX_NO_CONS_DEFINE_MEMBERS_WITH_PROPERTIES ODRX_NO_CONS_DEFINE_MEMBERS_WITH_PROPERTIES
#define GCRX_DXF_DEFINE_MEMBERS_WITH_PROPERTIES ODRX_DXF_DEFINE_MEMBERS_WITH_PROPERTIES
