#pragma once
#include "../rxmember.h"
#define GcRxEnumTag OdRxEnumTag
#define GcRxMember OdRxMember


#define GcRxMemberImpl OdRxMemberImpl
#define GcRxFacetProvider OdRxFacetProvider
#define GcRxMemberReactor OdRxMemberReactor
#define GcRxMemberIterator OdRxMemberIterator
#define GcRxMemberOverrule OdRxMemberOverrule
#define GcRxMemberCollection OdRxMemberCollection
#define GcRxMemberQueryEngine OdRxMemberQueryEngine
#define GcRxMemberQueryContext OdRxMemberQueryContext
#define GcRxMemberCollectionImp OdRxMemberCollectionImp
#define GcRxPromotingQueryContext OdRxPromotingQueryContext
#define GcRxMemberCollectionBuilder OdRxMemberCollectionBuilder