#pragma once
#include "../../../grx/PAL/api/def.h"
#include "acad2grx.h"

#define ACPAL_PORT GCPAL_PORT
#define AC_NON_CROSS_PLATFORM_API GC_NON_CROSS_PLATFORM_API
#define ACPAL_SUPPRESS_IMPEXP_DIRECTIVES GCPAL_SUPPRESS_IMPEXP_DIRECTIVES